### ISSUE TITLE
Publish build artifacts directly on github

### ISSUE THREAD

**Issue by DzmitryShylovich** [JSteunou/webstomp-client#10]
It would be nice if you publish latest stable artifacts directly in this repo so files can be served by https://rawgit.com/

Here is an example of such setup https://github.com/sockjs/sockjs-client/blob/master/dist/sockjs-0.3.4.js

**Comment by JSteunou** [comment]
Not a big fan of versioning build files for the same reason I dont put binaries, event if in the JS case it is plain text. What's the point of using rawgit.com over npm ?

**Comment by DzmitryShylovich** [comment]
I need to check if this library still compatible with my [backend](http://docs.spring.io/spring/docs/current/spring-framework-reference/html/websocket.html) as it was with original stompjs. I want the simplest possible setup - add script tag with reference to cdn, without npm, installations etc. It's just for convenience. 

I also don't like versioning here. Common practice is to include the latest stable file without version for example https://github.com/twbs/bootstrap/blob/master/dist/js/bootstrap.js

**Comment by JSteunou** [comment]
by versioning I mean using git for those file, not especially the suffix of the file.

**Comment by DzmitryShylovich** [comment]
Ok, so I think we can close this.
