### ISSUE TITLE
Client sends wrong CONNECT headers on reconnect

### ISSUE THREAD

**Issue by mschipperheyn** [JSteunou/webstomp-client#18]
I've run into a problem where during a reconnect, headers are included in the CONNECT message that were part of a previous SEND message, specifically the 'destination' header. This leads to problems for me. Not entirely sure yet how it happens

**Comment by mschipperheyn** [comment]
Looks like this:

```
    [ReconnectingWebSocket] ws.onopen http://www.project.com.br/msa/ws/websocket/
    index.ios.bundle:81406[ReconnectingWebSocket] resetting reconnection interval
    index.ios.bundle:81406[ReconnectingWebSocket] this.send http://www.project.com.br/msa/ws/websocket/ CONNECT
    Content-Type:application/json
    X-Requested-With:XMLHttpRequest
    X-Source-Header:WS
    accept-version:1.2,1.1,1.0
    heart-beat:10000,10000
    id:sub-0
    destination:/mobile-server/ping
```

**Comment by JSteunou** [comment]
Looking at the code I do not think this is possible. `headers` are parsed from client `connect` call, and this is a different object from `send`  call.

Maybe it is from your usage. Are you using the same referenced object for your headers?

**Comment by JSteunou** [comment]
any more input ?

**Comment by mschipperheyn** [comment]
I resolved this in the meantime. The reason for my problem if I vaguely recall but not coherently enough to put into writing
