### ISSUE TITLE
Support install via Bower

### ISSUE THREAD

**Issue by 9you** [JSteunou/webstomp-client#19]
Hi, I'm using the original version by **jmesnil** via Bower. But that version is no longer maintained, and I want to move to your library.
Can you provide support to install your project via Bower? Thanks!

**Comment by JSteunou** [comment]
Since npm became the de facto javascript package manager and others like
bower support install from github I wont

**Comment by 9you** [comment]
I don't think your project can be import directly from Github via Bower.

**Comment by JSteunou** [comment]
If you dont use es6 i might add the dist folder to github

**Comment by 9you** [comment]
Great. Thanks a lot!

**Comment by JSteunou** [comment]
I just added the dist folder to github so users like you that use another package manager than npm can point to github.
