### ISSUE TITLE
Apparently broken when using over SockJS

### ISSUE THREAD

**Issue by wgorder** [JSteunou/webstomp-client#2]
Loving the ES6 and webpack.  Unfortunately I cannot use yet.  It seems it does not work over SockJS.  I am working on a sample application based loosly on Rossen's here:

https://github.com/rstoyanchev/spring-websocket-portfolio/blob/master/src/main/webapp/static/js/services.js

All the internal refs appear to be null during creation (see the init function) leading to the first assign to fail I believe it was some binary thing.  Not sure if you have tested this or not.  I went back to the original one and it appears to be working fine.

Thanks,

**Comment by JSteunou** [comment]
Bug was in `webstomp.over`. Thank you for noticing it. Would make a patch release this week.

**Comment by JSteunou** [comment]
published on npm
