### ISSUE TITLE
Temporary queues example

### ISSUE THREAD

**Issue by pantonis** [JSteunou/webstomp-client#22]
How do we create a temporary queue and bind this to an exchange?

Thanks

**Comment by JSteunou** [comment]
It depends the broker you are using. Prefix of the destination is significant (like `/topic` for durable queue) Moreover options to broker queue creation can generally be sent via headers.

Look at https://www.rabbitmq.com/stomp.html section _destination_ for example

**Comment by JSteunou** [comment]
@pantonis if you find your answer could you right it down here so users with the same question wont be frustrated?
Also might helper me to improve the doc.
