### ISSUE TITLE
Documentation insufficient to move from original library

### ISSUE THREAD

**Issue by askaribragimov** [JSteunou/webstomp-client#25]
The documentation about moving from perfectly documented original library to this one is actually missing. 

There was method _over_ that worked with SockJS for me. Currently doc says

"over(ws, [options])
Takes a WebSocket alike object instance to return a webstomp Client object. "

Initailly, it is confusing to guess what would be the "websocket alike object". To my understanding, the only thing that should be present in technical documentation is exact codebase types, so readed won't left to guessing.

Usage of this functiuon in place of old call is resulting in

vendor.js:118 TypeError: WebSocket.over is not a function
    at doInitConnections (mainPageController.js:355)
    at m.$scope.initConnections (mainPageController.js:332)
    at fn (eval at compile (vendor.js:233), <anonymous>:4:236)
    at b (vendor.js:126)
    at e (vendor.js:276)
    at m.$eval (vendor.js:145)
    at m.$apply (vendor.js:146)
    at HTMLButtonElement.<anonymous> (vendor.js:276)

while JS file should be attached to the code. 

Kindly provide enough documentation to start using the library and migrating from original library.

**Comment by JSteunou** [comment]
Kindly provide example of code so I can help you. I can assure you `over` works.

**Comment by JSteunou** [comment]
Closing this for absence of feedbacks.
