### ISSUE TITLE
e6 not working

### ISSUE THREAD

**Issue by basz** [JSteunou/webstomp-client#27]
Hi!

I can't import the e6 module...

Error: Could not find module `webstomp-client` imported from `plhw-client/services/realtime-stomp`

```
npm install webstomp-client --save-dev
ember serve
```

```
// services/realtime-stomp.js
import webstomp from 'webstomp-client';

...
```

**Comment by mschipperheyn** [comment]
Works fine for me. Why are you saving in --save-dev mode?

**Comment by JSteunou** [comment]
@basz sorry to read that but it works for me too.

**Comment by basz** [comment]
nvm. solved it somehow. can't remember what went wrong. thx
