### ISSUE TITLE
Request: release with type definitions

### ISSUE THREAD

**Issue by mmrath** [JSteunou/webstomp-client#31]
Hi 

Do you think you can do a release with the newly added type definitions?
Also I noticed that 1.0.4 is not available in npm registry.

Thanks
Murali

**Comment by JSteunou** [comment]
Yes I plan to do that, I just need to find some time :)

**Comment by hakandilek** [comment]
really like to see a 1.0.4 release on npm

**Comment by JSteunou** [comment]
new version 1.0.5 is up
