### ISSUE TITLE
Setting only outgoing or incoming heartbeat alone leads to "Processing error"

### ISSUE THREAD

**Issue by phones24** [JSteunou/webstomp-client#32]
The headers are:
> login:guest
> passcode:guest
> host:/
> accept-version:1.2,1.1,1.0
> heart-beat:5000

Looks like RabbitMQ expecting both incoming and outgoing params in "heart-beat" header and library doesn't send both in this particular case.

**Comment by JSteunou** [comment]
heartbeat in client options must be `false` or an object with `{outgoing, incoming}` keys, not a number.
heart-beat manually set in header must be a string representing correct heart-beat value like `10,10`

I do not think this is a bug from this library, but from your usage of it.
