### ISSUE TITLE
Version 1.05 from npm doesn't include index.d.ts

### ISSUE THREAD

**Issue by gotson** [JSteunou/webstomp-client#34]
Hello,

when installing the latest version from npm, the file `index.d.ts` is not present at the root of the `webstomp-client` folder in `node_modules`.

I'm importing the module in an Angular2 app like this:
`import * as WebStomp from 'webstomp-client';`

It works fine if i add the file `index.d.ts` manually though.

**Comment by JSteunou** [comment]
Ho I'm sorry I forgot to add the `*.ts` inside package.json `files` attribute
