### ISSUE TITLE
Send text message on topic

### ISSUE THREAD

**Issue by oufresh** [JSteunou/webstomp-client#37]
Hello, can you please tell me if it is possible to send text messages to an ActiveMq Topic? I tried to do this but testing with a Java program it tells me that on the topic there is an ActiveMQBytesMessage not a TextMessage.
It is possible to do it directly from the javascript client or I had to call my server to send a text message to the topic?
Many thanks

**Comment by JSteunou** [comment]
Yes you can send from JS client, check out the example and RabbitMQ webstomp documentation
