### ISSUE TITLE
Diferences between Firefox and Chrome

### ISSUE THREAD

**Issue by luisclaudiogama** [JSteunou/webstomp-client#41]
Hi, first at all, congrats for this job.

  I observed a difference between Firefox and Chrome after lost connection ( this can be view at broadcast.html example ). Using Chrome, onError is called after several PINGS sent and Firefox calls onError after the first PING to change status ( disconnnected ).
 For me the Chrome´s behavior is better.

thanks

**Comment by JSteunou** [comment]
I'm sorry, I did not understand what is the question or the issue exactly here?

**Comment by luisclaudiogama** [comment]
Excuse me for my issue explanation is not so clear.
I changed the heart-beat to {30000,30000} .

When I´m using Chrome, and lost internet connection...Chrome continue sending PING bytes ( each 30s according heart-beat ) until to confirm the lost connection and calls onError. It´s ok!
So when I´m change to firefox and lost connection...it´s close the connection 10 seconds after and do not respect heart-beat "PING" byte. Firefox close the connection before it send the next PING.
It seems the Firefox don´t check "PONG" bytes.
Look this using chrome:
![chrome_webstomp](https://cloud.githubusercontent.com/assets/21362250/25397111/7f1f5622-29bd-11e7-9914-540d53585f1b.png)
Now using Firefox:
![firefox_webstomp](https://cloud.githubusercontent.com/assets/21362250/25397112/7f20defc-29bd-11e7-9436-9e4f11c6b2b8.png)

I hope I have been clearer than before.

Thank you very much

**Comment by JSteunou** [comment]
It seems Chrome try to keep the socket open in case of future reconnection while firefox detect it sooner. But again, what are you expecting me to do?

**Comment by luisclaudiogama** [comment]
I think heartbeat was necessary to check if server is alive, but I´m commited a mistake.
Thanks for your response and congrats for your job.

**Comment by JSteunou** [comment]
no problem
