### ISSUE TITLE
Subscription to second channel overrides the first subscriber

### ISSUE THREAD

**Issue by kuceram** [JSteunou/webstomp-client#43]
This error happens when you send headers object to subscription method like this:

```
var headers = {'Authorization': `Bearer 123`};
var subscription1 = client.subscribe(destination1, callback1, headers);
var subscription2 = client.subscribe(destination2, callback2, headers);
```

If you do the second subscription you loose the reference to the first one (callback `destination1` is never called). This issue came due to the fact that you break the atomicity rule:
https://github.com/JSteunou/webstomp-client/blob/master/src/client.js#L269

You should not manipulate object that are coming from outside.

**Comment by JSteunou** [comment]
Interesting, I suppose calling `subscribe` with a clone of `headers` fix the issue temporary, does it?

**Comment by kuceram** [comment]
Yes it does. But I would suggest to do a clone internally within the subscribe method as method user might not be aware of this. It is also hard to debug this inconvenient.

**Comment by JSteunou** [comment]
@kuceram is that ok for you?

**Comment by kuceram** [comment]
Hi, sorry for late respond. I will check it out as soon as possible and let you know. :-)

**Comment by kuceram** [comment]
Works fine, now...
