### ISSUE TITLE
Wrong error type in error callback

### ISSUE THREAD

**Issue by roddolf** [JSteunou/webstomp-client#47]
The typings of the `errorCallback` have that the returned error is a `string`, but in reality its an error `Frame` or a `CloseEvent`.

**Comment by JSteunou** [comment]
I assume you are talking about the typescript definition. I am not maintaining it I accept PR from typescript community. If the typescript community is not capable of maintaining it I will remove it. That was my only condition when I accepted the PR that add it the 1st time.
