### ISSUE TITLE
Symbol is undefined after ws connected

### ISSUE THREAD

**Issue by Lucas0819** [JSteunou/webstomp-client#48]
After websocket connected the "Symbol" is undefined while using IE11.
And ws is not work.
![image](https://user-images.githubusercontent.com/31462754/30356109-d7a1526c-9869-11e7-98ba-545fb7a6e6b9.png)
When I use **Chrome** to connect ws, "Symbol" is a function.
![image](https://user-images.githubusercontent.com/31462754/30356154-05b73072-986a-11e7-98b7-a754279c63c8.png)

location: /dist/webstomp.js    line 757.

used npm to install the webstomp-client.
version:  "webstomp-client": "^1.0.7"

**Comment by JSteunou** [comment]
If you need `Symbol` you should polyfill it with babel-polyfill or polyfill.io but that is not related to webstomp-client

**Comment by Lucas0819** [comment]
thanks~

**Comment by romerod** [comment]
@JSteunou the generated webstomp.js is currently using Symbol and only works with IE11 when using the babel-polyfill, is this wanted?

For example:
https://github.com/JSteunou/webstomp-client/blob/master/dist/webstomp.js#L39

**Comment by JSteunou** [comment]
Yes it is. Like I said above

> If you need Symbol you should polyfill it with babel-polyfill or polyfill.io but that is not related to webstomp-client

**Comment by romerod** [comment]
I know it works with the polyfill, I just wanted to say that it is related to the webstomp client as Symbol is used in the distributed file, see link in previous comment
________________________________
