### ISSUE TITLE
Custom logs with frame object as the 2nd param

### ISSUE THREAD

**Issue by zatziky** [JSteunou/webstomp-client#55]
Hi there,

this is a kind of a feature request. I am aware that it's possible to override the logs via `client.debug = (log) => ...myLogic`. It is cumbersome to do anything with the plain text. You could send the text and, as the 2nd parameter, the **frame object**. Then we developers can strip headers, shorten some access tokens, etc. ...

At the moment the debug methods accepts a vararg `...args`. Every method in **src/client.js** is using only 1 arg (the message). See the code:

```
debug(...args) {
        if (this.hasDebug) console.log(...args);
}
```

I will create a PR in a moment so that you can verify it will make no harm, you'll see.

**Comment by zatziky** [comment]
Here is the promised PR - https://github.com/JSteunou/webstomp-client/pull/56

**Comment by zatziky** [comment]
Hey @JSteunou, what is your opinion?

**Comment by JSteunou** [comment]
If I understand well you just need more info in the log like the content of a frame. I could do that, but not the way you did in your PR.

**Comment by zatziky** [comment]
@JSteunou I need to customize the data that is logged and the text is not the best fit. Of course, I don't mind if you do it in a different way.

**Comment by JSteunou** [comment]
Could you test #58 and tell me if it matches your need?

**Comment by zatziky** [comment]
@JSteunou Right in the morning I'll check it!
