### ISSUE TITLE
headerLines.reverse() error in stomp.js

### ISSUE THREAD

**Issue by kashsbd** [JSteunou/webstomp-client#63]
undefined is not a function (evaluating 'headerLines.reverse()typeof Symbol === 'function' ? Symbol.iterator :'@@iterator'') 

 When I connect two android devices simultaneously, I encounter this error.  

Please help me!  

Thanks in advance.

**Comment by JSteunou** [comment]
maybe you should find by yourself first why you have an `undefined` value. This tool can help https://developers.google.com/web/tools/chrome-devtools/
