### ISSUE TITLE
Mismatch Between Sec-WebSocket-Protocol & accept-version

### ISSUE THREAD

**Issue by dansiviter** [JSteunou/webstomp-client#66]
It's possible for the headers to state:

```
GET ws://myhost:8080/websocket HTTP/1.1
Host: myhost:8080
Connection: Upgrade
...
Sec-WebSocket-Protocol: v11.stomp, v12.stomp  // <-- only v1.1 and v1.2
```
But the `CONNECT` frame to state:
```
CONNECT
accept-version:1.2,1.1,1.0   // <-- Are we able to accept 1.0?
```

IMO, I don't think it's valid to declare the STOMP protocol on the `Sec-WebSocket-Protocol` header and then disregard it in the `accept-version`. 

Issue found in v1.2.0.

**Comment by JSteunou** [comment]
Thanks I will look into it

**Comment by JSteunou** [comment]
Indeed, if you enforce `protocols` with specific versions, those are not used to compute the STOMP `accept-version` in the `CONNECT` frame

Not sure if this could have some negative impact though

**Comment by JSteunou** [comment]
Fixed in https://github.com/JSteunou/webstomp-client/releases/tag/1.2.2
