### ISSUE TITLE
Typescript definition file

### ISSUE THREAD

**Issue by cexbrayat** [JSteunou/webstomp-client#7]
First of all, thank you very much for the energy you're putting in the project.

I am, as a lot of Angular 2 developers, working more and more with TypeScript.
And, as you may know, TypeScript needs typings for external librairies. So it would be great if you could add the typings to the [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) repository, or better, within the NPM module (as recent TypeScript compilers can pick it up automatically).

This is not a new issue, as you can see on the original repo https://github.com/jmesnil/stomp-websocket/issues/61

I'm not a TypeScript expert, but I slightly modified one of the propositions to have the bare minimum for my case (I don't know enough the library to make something more exhaustive).

``` typescript
declare module 'webstomp-client' {

  interface webstomp {
    over(socketType: any) : webstomp;
    connect(headers: any, connectCallback: () => any);
    subscribe(destination: string, callback: (message: StompMessage) => any);
  }

  interface StompMessage {
    body : string;
  }

  var webstomp: webstomp;
  export = webstomp;

}
```

**Comment by JSteunou** [comment]
I am sorry I do not know enough about Typescript. Does this mean that you cannot use this library without types definition?

**Comment by cexbrayat** [comment]
You can use it, but the compiler will complain (or won't even compile depending on your settings).
If the fork gain in popularity, we can expect a few people with the same need.

The ideal would be to embed a `webstomp-client.d.ts` file in the `dist` directory of the NPM module (see http://www.typescriptlang.org/docs/handbook/typings-for-npm-packages.html for more info).
This file would contain roughly what I proposed (until a better TypeScript developer than me offers something better), although it lacks a few useful methods (like `unsubscribe` and others you'll think about).

With this, the TypeScript compiler should be happy.

**Comment by JSteunou** [comment]
I will think about it. On one hand I want to provide what's needed for this library, on the other hand I cannot spread efforts to please everyone using a JavaScript like language with specific files to add and mostly to maintain. What's the worst? Compiler with warning, or compiler with error because the `.ts` is not up to date?

**Comment by cexbrayat** [comment]
I completely understand, take your time. I think it would be a great help for TS developers who will have to find this file, but I understand your reluctance to maintain it.

**Comment by mishtt** [comment]
I am kind of stuck in the same boat - I need the typings so that I can use it in my current project. I have not found a work around 3 days into working with the library. it would be wonderful to have it but I would understand if its not a priority.

**Comment by JSteunou** [comment]
I see. Could it work for you guys with https://github.com/DefinitelyTyped/DefinitelyTyped ?
If you guys can handle this `.ts` for your need by yourself it would help me a lot as I know nothing about TypeScript.

**Comment by mishtt** [comment]
Yes that would work - the ideal would be what @cexbrayat mentioned but yes if we could get something in DT then that would go a long way. I work for a major airline and we are in the process of adopting libraries for our core boiler plate project which will serve as a starter project for all new UI projects. I can help out if need be to maintain the definitions

**Comment by sinedsem** [comment]
That's so sad this issue is in "open" state... I am starting a new project, and I really need typings for this library. Any solutions right now?

**Comment by JSteunou** [comment]
I could take a PR but I am afraid I could not maintain the file when the
lib will evolve. I need someone to take this in charge.

**Comment by sinedsem** [comment]
I am a newbie in frontend, that's why I need this out of the box. I don't understand yet how this works, so I completely agree: we need somebody in charge.

**Comment by JimiC** [comment]
Typings are now available at [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/types-2.0/stompjs) `types-2.0` branch.

**Comment by JimiC** [comment]
Typings for `stompjs`are now available at [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/types-2.0/stompjs) `types-2.0` branch.
